### PR TITLE
Add strong mode configuration and fix analyzer warnings.

### PR DESCRIPTION
**Pull request by alexeieleusis**
Fixes https://github.com/polux/adts/issues/1

### CODE REVIEW

**Comment by alexeieleusis** [comment]
Any interest on cleaning lints? Using https://github.com/dart-lang/linter

**Comment by polux** [comment]
Thanks for this! Maybe add yourself to the list of authors in these files before I merge this?

**Comment by alexeieleusis** [comment]
Done.

Of course I contribute these changes to be used with the same license the code originally had.

I assumed is implicit, but better said than not.

**Comment by polux** [comment]
Thanks!

**Pull request merged**
